name: Deploy Multiple React Apps

on:
  push:
    branches:
      - main  # or "master" if that's your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build todo-list
        run: |
          cd React/Assignment/todo-list
          npm install
          npm run build
          mkdir -p ../../../builds/todo-list
          cp -r build/* ../../../builds/todo-list

      - name: Build portfolio
        run: |
          cd Projects/Project-3_React/portfolio
          npm install
          npm run build
          mkdir -p ../../../builds/portfolio
          cp -r build/* ../../../builds/portfolio

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: builds
